version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: raviosa-api
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: always
