name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract the current version
        id: extract_version
        run: |
          VERSION_FILE="VERSION"
          if [ -f "$VERSION_FILE" ]; then
            VERSION=$(cat $VERSION_FILE)
          else
            VERSION="1.0.0"
          fi
          echo "Current version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Increment patch version
        id: increment_version
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ steps.extract_version.outputs.version }}"
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          echo $NEW_VERSION > VERSION
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Build Docker image
        run: docker-compose build

      - name: Tag Docker image
        run: |
          IMAGE_NAME=spectrashohan/raviosa-api
          docker tag api:latest $IMAGE_NAME:v${{ steps.increment_version.outputs.new_version }}

      - name: Push Docker image to DockerHub
        run: |
          IMAGE_NAME=spectrashohan/raviosa-api
          docker push $IMAGE_NAME:v${{ steps.increment_version.outputs.new_version }}

      - name: Commit new version to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add VERSION
          git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"
          git push
